#版本号
[versions]
#基础环境版本
gradle = "7.0.3"
kotlin = "1.5.31"
compileSdk = "31"
minSdk = "21"
targetSdk = "31"

material = "1.3.0"
constraintlayout = "1.0.0-alpha07"
swiperefresh = "0.16.1"
#导航
navigation = "2.4.0-alpha10"
#compose相关
compose = "1.0.5"
activity-compose = "1.3.1"
viewmodel-compose = "1.0.0-alpha07"
hilt-navigation-compose = "1.0.0-alpha03"
#分页
paging-compose = "1.0.0-alpha14"
#依赖注入
hilt-dagger = "2.35"
hilt-viewmodel="1.0.0-alpha01"
#网络请求
retrofit = "2.9.0"
okhttp = "4.9.0"
#图片加载
coil = "1.4.0"
#数据库
room-runtime = "2.3.0"
room-paging = "2.4.0-rc01"
#测试
junit = "4.+"
androidx-junit = "1.1.2"
androidx-espresso-core = "3.4.0"


#依赖库
[libraries]
build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
#控件
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout" }
swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "swiperefresh" }
#compose相关
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewmodel-compose" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
#分页
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }
#依赖注入
hilt-android-runtime = { module = "com.google.dagger:hilt-android", version.ref = "hilt-dagger" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-dagger" }
#网络请求
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
#图片加载
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
#数据库
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room-paging" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
#测试
junit = { module = "junit:junit", version.ref = "junit" }

androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso-core" }
compose-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }



[bundles]
#compose相关
compose = ["activity-compose", "compose-material", "compose-animation", "compose-ui-tooling",
    "navigation-compose", "viewmodel-compose", "hilt-navigation-compose", "paging-compose"]
#网络请求
net-request = ["retrofit", "moshi", "okhttp", "logging-interceptor"]
#数据库
room = ["room-runtime", "room-ktx"]
#测试
test = ["androidx-junit", "androidx-espresso-core", "compose-junit4"]




